### ISSUE TITLE
Question:how does contract work in byteball?

### ISSUE THREAD

**Issue by Skyge** [byteball/byteball#392]
I have read the whitepaper already, but I am confused with the part of contract. In the byteball, a contract is just like a script, but when two people sign a data together, how this unit work? Or, how contract works?  Thanks for help.

**Comment by tarmo888** [comment]
Smart contracts on Byteball are not scripts like Solidity code on Ethereum. Instead, Byteball smart contract is basically any address, which has set of conditions that need to be true in order to spend from that address.

So, multi-sig address has conditions like these
https://github.com/byteball/byteballcore/wiki/Smart-contracts#r-of-set

There are more conditions that can be used and there are code examples in multiple bot repositories, but I would suggest you do join official Slack #tech channel to get answers to your questions https://slack.byteball.org/

**Comment by Skyge** [comment]
Thanks for your help,I will have a try.
